[2016-08-01 18:49:14 +0000] [49469] [INFO] Starting gunicorn 19.6.0
[2016-08-01 18:49:14 +0000] [49469] [INFO] Listening at: http://127.0.0.1:8000 (49469)
[2016-08-01 18:49:14 +0000] [49469] [INFO] Using worker: sync
[2016-08-01 18:49:14 +0000] [49474] [INFO] Booting worker with pid: 49474
[2016-08-01 18:49:14 +0000] [49474] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
ImportError: No module named wsgi
[2016-08-01 18:49:14 +0000] [49474] [INFO] Worker exiting (pid: 49474)
[2016-08-01 18:49:14 +0000] [49469] [INFO] Shutting down: Master
[2016-08-01 18:49:14 +0000] [49469] [INFO] Reason: Worker failed to boot.
